import path from 'node:path';
import { createCanvas, GlobalFonts, type Image } from '@napi-rs/canvas';
import { ensureFonts } from '../eco/render.js';

/**
 * The tombstone for /generate rip, and the word wrap it uses. (The fake Discord screens are in discord.ts.) These are jokes,
 * not evidence: every image carries a small "generated" notice so it can't be passed off as a real screenshot.
 */

const ASSETS = path.resolve(import.meta.dir, '../../assets/fonts');
let emojiReady = false;
function fonts() {
  ensureFonts();
  if (!emojiReady) { try { GlobalFonts.registerFromPath(path.join(ASSETS, 'twemoji.otf'), 'Emoji'); } catch { /* emoji fall back to system fonts */ } emojiReady = true; }
}
const F = (px: number, bold = false) => `${bold ? 'bold ' : ''}${px}px ${bold ? 'RankB' : 'Rank'}, Emoji, sans-serif`;

export const NOTICE = 'Generated by Bestow · not a real screenshot';

export type Measure = (s: string) => number;

/** Greedy word wrap; words longer than the line are split by character. Preserves explicit newlines. */
export function wrapText(measure: Measure, text: string, maxWidth: number): string[] {
  const out: string[] = [];
  for (const para of text.split(/\r?\n/)) {
    let line = '';
    for (const word of para.split(/\s+/).filter(Boolean)) {
      let w = word;
      while (measure(w) > maxWidth) {
        let n = w.length;
        while (n > 1 && measure(w.slice(0, n)) > maxWidth) n--;
        if (line) { out.push(line); line = ''; }
        out.push(w.slice(0, n)); w = w.slice(n);
      }
      const trial = line ? `${line} ${w}` : w;
      if (measure(trial) <= maxWidth) line = trial; else { if (line) out.push(line); line = w; }
    }
    out.push(line);
  }
  return out;
}

// ─── Tombstone ───────────────────────────────────────────────────────────────

export function renderRip(o: { name: string; dates?: string; epitaph?: string; avatar?: Image | null }): Buffer {
  fonts();
  const W = 600, H = 700;
  const c = createCanvas(W, H), ctx = c.getContext('2d');
  const sky = ctx.createLinearGradient(0, 0, 0, H); sky.addColorStop(0, '#1b1f3a'); sky.addColorStop(1, '#3a3f66');
  ctx.fillStyle = sky; ctx.fillRect(0, 0, W, H);
  ctx.fillStyle = '#2e3a2a'; ctx.fillRect(0, H - 110, W, 110); // ground
  // Moon
  ctx.fillStyle = '#f4f1de'; ctx.beginPath(); ctx.arc(500, 90, 38, 0, Math.PI * 2); ctx.fill();
  // Stone
  const sx = 110, sw = 380, sy = 150, sh = H - 150 - 60;
  ctx.fillStyle = '#8d8f98';
  ctx.beginPath(); ctx.moveTo(sx, sy + sh); ctx.lineTo(sx, sy + sw / 2); ctx.arc(sx + sw / 2, sy + sw / 2, sw / 2, Math.PI, 0); ctx.lineTo(sx + sw, sy + sh); ctx.closePath(); ctx.fill();
  ctx.strokeStyle = '#6d6f77'; ctx.lineWidth = 6; ctx.stroke();
  ctx.textAlign = 'center';
  ctx.fillStyle = '#3d3f46'; ctx.font = F(46, true); ctx.fillText('R.I.P', W / 2, sy + 110);
  if (o.avatar) {
    ctx.save(); ctx.beginPath(); ctx.arc(W / 2, sy + 190, 50, 0, Math.PI * 2); ctx.clip();
    ctx.filter = 'grayscale(1)'; ctx.drawImage(o.avatar, W / 2 - 50, sy + 140, 100, 100); ctx.restore();
    ctx.strokeStyle = '#3d3f46'; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(W / 2, sy + 190, 50, 0, Math.PI * 2); ctx.stroke();
  }
  const namey = sy + (o.avatar ? 290 : 220);
  ctx.fillStyle = '#2b2d33'; ctx.font = F(34, true);
  const nameLines = wrapText(s => ctx.measureText(s).width, o.name.slice(0, 60), sw - 50).slice(0, 2);
  nameLines.forEach((t, i) => ctx.fillText(t, W / 2, namey + i * 40));
  ctx.font = F(20); ctx.fillStyle = '#42444c';
  ctx.fillText(o.dates ?? '', W / 2, namey + nameLines.length * 40 + 8);
  if (o.epitaph) {
    ctx.font = F(19); ctx.fillStyle = '#42444c';
    wrapText(s => ctx.measureText(s).width, `“${o.epitaph.slice(0, 120)}”`, sw - 60).slice(0, 3).forEach((t, i) => ctx.fillText(t, W / 2, namey + nameLines.length * 40 + 50 + i * 26));
  }
  ctx.font = F(11); ctx.fillStyle = '#c9cbd6'; ctx.textAlign = 'right'; ctx.fillText(NOTICE, W - 12, H - 8);
  return c.toBuffer('image/png');
}
