import path from 'node:path';
import { createCanvas, GlobalFonts, type Image, type SKRSContext2D } from '@napi-rs/canvas';
import { ensureFonts } from '../eco/render.js';

/**
 * Fake-chat and tombstone images for /generate. These are jokes, not evidence: every image carries a small
 * "generated" notice so it can't be passed off as a real screenshot.
 */

const ASSETS = path.resolve(import.meta.dir, '../../assets/fonts');
let emojiReady = false;
function fonts() {
  ensureFonts();
  if (!emojiReady) { try { GlobalFonts.registerFromPath(path.join(ASSETS, 'twemoji.otf'), 'Emoji'); } catch { /* emoji fall back to system fonts */ } emojiReady = true; }
}
const F = (px: number, bold = false) => `${bold ? 'bold ' : ''}${px}px ${bold ? 'RankB' : 'Rank'}, Emoji, sans-serif`;

export const MAX_MESSAGES = 8;
export const MAX_TEXT = 500;
export const NOTICE = 'Generated by Bestow · not a real screenshot';

export type Measure = (s: string) => number;

/** Greedy word wrap; words longer than the line are split by character. Preserves explicit newlines. */
export function wrapText(measure: Measure, text: string, maxWidth: number): string[] {
  const out: string[] = [];
  for (const para of text.split(/\r?\n/)) {
    let line = '';
    for (const word of para.split(/\s+/).filter(Boolean)) {
      let w = word;
      while (measure(w) > maxWidth) {
        let n = w.length;
        while (n > 1 && measure(w.slice(0, n)) > maxWidth) n--;
        if (line) { out.push(line); line = ''; }
        out.push(w.slice(0, n)); w = w.slice(n);
      }
      const trial = line ? `${line} ${w}` : w;
      if (measure(trial) <= maxWidth) line = trial; else { if (line) out.push(line); line = w; }
    }
    out.push(line);
  }
  return out;
}

export interface ChatLine { name: string; color?: string; avatar?: Image | null; text: string; time?: string; replyTo?: { name: string; text: string; color?: string } }
export type Theme = 'dark' | 'light';

const THEMES = {
  dark: { bg: '#313338', text: '#dbdee1', muted: '#949ba4', reply: '#b5bac1', name: '#ffffff' },
  light: { bg: '#ffffff', text: '#313338', muted: '#5c5e66', reply: '#4e5058', name: '#060607' },
} as const;

export const DEFAULT_COLORS = ['#f47b67', '#e78284', '#5865f2', '#57f287', '#fee75c', '#eb459e', '#3ba55d', '#faa61a'];
export const colorFor = (name: string) => DEFAULT_COLORS[[...name].reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 7) % DEFAULT_COLORS.length]!;

function circleAvatar(ctx: SKRSContext2D, img: Image | null | undefined, x: number, y: number, size: number, fallback: string) {
  ctx.save();
  ctx.beginPath(); ctx.arc(x + size / 2, y + size / 2, size / 2, 0, Math.PI * 2); ctx.clip();
  if (img) ctx.drawImage(img, x, y, size, size);
  else { ctx.fillStyle = fallback; ctx.fillRect(x, y, size, size); }
  ctx.restore();
}

export function renderChat(lines: ChatLine[], opts: { theme?: Theme; width?: number } = {}): Buffer {
  fonts();
  const th = THEMES[opts.theme ?? 'dark'];
  const W = opts.width ?? 720, LEFT = 72, RIGHT = 20, TEXT_W = W - LEFT - RIGHT, LH = 22;
  const probe = createCanvas(10, 10).getContext('2d');
  probe.font = F(16);
  const measure: Measure = s => probe.measureText(s).width;

  // Layout pass
  type Row = { line: ChatLine; head: boolean; wrapped: string[]; y: number; h: number };
  const rows: Row[] = [];
  let y = 14;
  lines.slice(0, MAX_MESSAGES).forEach((line, i) => {
    const prev = lines[i - 1];
    const head = !prev || prev.name !== line.name || !!line.replyTo;
    const wrapped = wrapText(measure, line.text.slice(0, MAX_TEXT), TEXT_W);
    const h = (line.replyTo ? 22 : 0) + (head ? 22 : 0) + wrapped.length * LH + (head ? 12 : 4);
    rows.push({ line, head, wrapped, y, h });
    y += h;
  });
  const H = Math.min(2400, y + 26);

  const c = createCanvas(W, H);
  const ctx = c.getContext('2d');
  ctx.fillStyle = th.bg; ctx.fillRect(0, 0, W, H);
  ctx.textBaseline = 'alphabetic';

  for (const r of rows) {
    let cy = r.y;
    const { line } = r;
    if (line.replyTo) {
      ctx.strokeStyle = th.muted; ctx.lineWidth = 2;
      ctx.beginPath(); ctx.moveTo(36, cy + 22); ctx.lineTo(36, cy + 10); ctx.quadraticCurveTo(36, cy + 4, 42, cy + 4); ctx.lineTo(58, cy + 4); ctx.stroke();
      circleAvatar(ctx, null, 62, cy - 1, 16, line.replyTo.color ?? colorFor(line.replyTo.name));
      ctx.font = F(14, true); ctx.fillStyle = line.replyTo.color ?? th.reply; const rn = `@${line.replyTo.name}`; ctx.fillText(rn, 84, cy + 12);
      ctx.font = F(14); ctx.fillStyle = th.reply;
      let rt = line.replyTo.text.replace(/\s+/g, ' ');
      const room = W - 84 - ctx.measureText(rn).width - 30;
      while (rt.length > 1 && ctx.measureText(rt).width > room) rt = rt.slice(0, -2);
      ctx.fillText(` ${rt}${rt !== line.replyTo.text.replace(/\s+/g, ' ') ? '…' : ''}`, 84 + ctx.measureText(rn).width, cy + 12);
      cy += 22;
    }
    if (r.head) {
      circleAvatar(ctx, line.avatar, 16, cy + 2, 40, line.color ?? colorFor(line.name));
      ctx.font = F(16, true); ctx.fillStyle = line.color ?? th.name; ctx.fillText(line.name, LEFT, cy + 18);
      const nameW = ctx.measureText(line.name).width; // measured while the bold 16px font is still set
      if (line.time) { ctx.font = F(12); ctx.fillStyle = th.muted; ctx.fillText(line.time, LEFT + nameW + 10, cy + 18); }
      cy += 22;
    }
    ctx.font = F(16); ctx.fillStyle = th.text;
    r.wrapped.forEach((t, k) => ctx.fillText(t, LEFT, cy + 16 + k * LH));
  }

  ctx.font = F(11); ctx.fillStyle = th.muted; ctx.textAlign = 'right'; ctx.fillText(NOTICE, W - 12, H - 8);
  return c.toBuffer('image/png');
}

// ─── Tombstone ───────────────────────────────────────────────────────────────

export function renderRip(o: { name: string; dates?: string; epitaph?: string; avatar?: Image | null }): Buffer {
  fonts();
  const W = 600, H = 700;
  const c = createCanvas(W, H), ctx = c.getContext('2d');
  const sky = ctx.createLinearGradient(0, 0, 0, H); sky.addColorStop(0, '#1b1f3a'); sky.addColorStop(1, '#3a3f66');
  ctx.fillStyle = sky; ctx.fillRect(0, 0, W, H);
  ctx.fillStyle = '#2e3a2a'; ctx.fillRect(0, H - 110, W, 110); // ground
  // Moon
  ctx.fillStyle = '#f4f1de'; ctx.beginPath(); ctx.arc(500, 90, 38, 0, Math.PI * 2); ctx.fill();
  // Stone
  const sx = 110, sw = 380, sy = 150, sh = H - 150 - 60;
  ctx.fillStyle = '#8d8f98';
  ctx.beginPath(); ctx.moveTo(sx, sy + sh); ctx.lineTo(sx, sy + sw / 2); ctx.arc(sx + sw / 2, sy + sw / 2, sw / 2, Math.PI, 0); ctx.lineTo(sx + sw, sy + sh); ctx.closePath(); ctx.fill();
  ctx.strokeStyle = '#6d6f77'; ctx.lineWidth = 6; ctx.stroke();
  ctx.textAlign = 'center';
  ctx.fillStyle = '#3d3f46'; ctx.font = F(46, true); ctx.fillText('R.I.P', W / 2, sy + 110);
  if (o.avatar) {
    ctx.save(); ctx.beginPath(); ctx.arc(W / 2, sy + 190, 50, 0, Math.PI * 2); ctx.clip();
    ctx.filter = 'grayscale(1)'; ctx.drawImage(o.avatar, W / 2 - 50, sy + 140, 100, 100); ctx.restore();
    ctx.strokeStyle = '#3d3f46'; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(W / 2, sy + 190, 50, 0, Math.PI * 2); ctx.stroke();
  }
  const namey = sy + (o.avatar ? 290 : 220);
  ctx.fillStyle = '#2b2d33'; ctx.font = F(34, true);
  const nameLines = wrapText(s => ctx.measureText(s).width, o.name.slice(0, 60), sw - 50).slice(0, 2);
  nameLines.forEach((t, i) => ctx.fillText(t, W / 2, namey + i * 40));
  ctx.font = F(20); ctx.fillStyle = '#42444c';
  ctx.fillText(o.dates ?? '', W / 2, namey + nameLines.length * 40 + 8);
  if (o.epitaph) {
    ctx.font = F(19); ctx.fillStyle = '#42444c';
    wrapText(s => ctx.measureText(s).width, `“${o.epitaph.slice(0, 120)}”`, sw - 60).slice(0, 3).forEach((t, i) => ctx.fillText(t, W / 2, namey + nameLines.length * 40 + 50 + i * 26));
  }
  ctx.font = F(11); ctx.fillStyle = '#c9cbd6'; ctx.textAlign = 'right'; ctx.fillText(NOTICE, W - 12, H - 8);
  return c.toBuffer('image/png');
}
