/**
 * Generates COMMANDS.md from the real command registry, so the reference can never drift from the code.
 *   bun run docs          → rewrite COMMANDS.md
 * tests/docs.test.ts fails if the committed file is out of date.
 */
import { categoryLabel, toHelp } from '../src/info/help';

export async function buildCommandsDoc(): Promise<string> {
  // Loading commands must never depend on (or read) a developer's real .env.
  Bun.env.DB_PATH = ':memory:'; Bun.env.LOG_LEVEL = 'warn'; Bun.env.TOKEN = 'docs'; Bun.env.CLIENT_ID = '1';
  const registry = (await import('../src/handlers/commandHandler')).default;
  const list = toHelp(registry.values());
  const byCat = new Map<string, typeof list>();
  for (const c of list) byCat.set(c.category, [...(byCat.get(c.category) ?? []), c]);
  const out: string[] = [
    '# Command reference',
    '',
    '> Generated by `bun run docs` from the live command registry — do not edit by hand.',
    '',
    `**${list.length} top-level commands** · **${list.reduce((n, c) => n + c.entries.length, 0)} invocable commands** (Discord\'s limit is 100 top-level).`,
    '',
    'Arguments: `<required>` `[optional]`.',
    '',
  ];
  for (const [cat, cmds] of [...byCat.entries()].sort((a, b) => categoryLabel(a[0]).localeCompare(categoryLabel(b[0])))) {
    out.push(`## ${categoryLabel(cat)}`, '');
    for (const c of cmds) {
      out.push(`### /${c.name}`, '', c.description, '');
      if (c.entries.length > 1 || c.entries[0]!.path !== c.name) {
        for (const e of c.entries) out.push(`- \`/${e.path}${e.options.length ? ` ${e.options.join(' ')}` : ''}\` — ${e.description}`);
      } else if (c.entries[0]!.options.length) out.push(`Options: ${c.entries[0]!.options.map(o => `\`${o}\``).join(' ')}`);
      out.push('');
    }
  }
  return `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

if (import.meta.main) {
  const doc = await buildCommandsDoc();
  await Bun.write(new URL('../COMMANDS.md', import.meta.url), doc);
  console.log(`COMMANDS.md written (${doc.split('\n').length} lines)`);
  process.exit(0);
}
